#**********************************************************************************#
# Copyright by @bkozdras <b.kozdras@gmail.com>                                     #
# Version: 1.0                                                                     #
# Licence: MIT                                                                     #
#**********************************************************************************#

function(append_to_include_directories projectName headersLib)
    get_target_property(includes ${headersLib} INTERFACE_INCLUDE_DIRECTORIES)
    set_property(TARGET ${projectName}
        APPEND PROPERTY
        INCLUDE_DIRECTORIES ${includes})
endfunction(append_to_include_directories)

function(add_pico_sdk_include_directories projectName)
    append_to_include_directories(${projectName} pico_base_headers)
    append_to_include_directories(${projectName} pico_binary_info_headers)
    append_to_include_directories(${projectName} pico_bit_ops_headers)
    append_to_include_directories(${projectName} pico_divider_headers)
    append_to_include_directories(${projectName} pico_stdlib_headers)
    append_to_include_directories(${projectName} pico_sync_headers)
    append_to_include_directories(${projectName} pico_time_headers)
    append_to_include_directories(${projectName} pico_usb_reset_interface_headers)
    append_to_include_directories(${projectName} pico_util_headers)
    append_to_include_directories(${projectName} hardware_regs)
    append_to_include_directories(${projectName} hardware_structs)
    append_to_include_directories(${projectName} hardware_adc_headers)
    append_to_include_directories(${projectName} hardware_base)
    append_to_include_directories(${projectName} hardware_claim_headers)
    append_to_include_directories(${projectName} hardware_clocks_headers)
    append_to_include_directories(${projectName} hardware_divider)
    append_to_include_directories(${projectName} hardware_dma_headers)
    append_to_include_directories(${projectName} hardware_exception_headers)
    append_to_include_directories(${projectName} hardware_flash_headers)
    append_to_include_directories(${projectName} hardware_gpio_headers)
    append_to_include_directories(${projectName} hardware_i2c_headers)
    append_to_include_directories(${projectName} hardware_interp_headers)
    append_to_include_directories(${projectName} hardware_irq_headers)
    append_to_include_directories(${projectName} hardware_pio_headers)
    append_to_include_directories(${projectName} hardware_pll_headers)
    append_to_include_directories(${projectName} hardware_pwm)
    append_to_include_directories(${projectName} hardware_resets)
    append_to_include_directories(${projectName} hardware_rtc_headers)
    append_to_include_directories(${projectName} hardware_spi_headers)
    append_to_include_directories(${projectName} hardware_sync_headers)
    append_to_include_directories(${projectName} hardware_timer_headers)
    append_to_include_directories(${projectName} hardware_uart_headers)
    append_to_include_directories(${projectName} hardware_vreg_headers)
    append_to_include_directories(${projectName} hardware_watchdog_headers)
    append_to_include_directories(${projectName} hardware_xosc_headers)
    append_to_include_directories(${projectName} pico_bootrom)
    append_to_include_directories(${projectName} pico_double_headers)
    append_to_include_directories(${projectName} pico_fix_rp2040_usb_device_enumeration)
    append_to_include_directories(${projectName} pico_float_headers)
    append_to_include_directories(${projectName} pico_int64_ops_pico)
    append_to_include_directories(${projectName} pico_multicore)
    append_to_include_directories(${projectName} pico_platform_headers)
    append_to_include_directories(${projectName} pico_printf_headers)
    append_to_include_directories(${projectName} pico_runtime)
    append_to_include_directories(${projectName} pico_stdio)
    append_to_include_directories(${projectName} pico_stdio_semihosting)
    append_to_include_directories(${projectName} pico_stdio_uart)
    append_to_include_directories(${projectName} pico_stdio_usb)
    append_to_include_directories(${projectName} pico_unique_id)
endfunction(add_pico_sdk_include_directories)
